### PR TITLE
Added typescript definition file.

### PR DESCRIPTION
**Pull request by MIrinkov**
#5 
Create a definition file that exports 3 functions.
The functions are typed as `void` by design - there is no usage of return values in the tests.

For maintainability it might be easy enough to just rewrite the library in TypeScript, but this file should solve most people's problems.

### CODE REVIEW

**Comment by hustcc** [comment]
When build, the file will be deleted.

**Comment by MIrinkov** [comment]
I ran the build script, the file was left there.

**Comment by MIrinkov** [comment]
I could provide a PR with the whole library rewritten in TS, if you like. Or I could just push the `index.d.ts` file to the Definitely Typed repo.

**Comment by hustcc** [comment]
You can rewrite all as you like.

Pay attention to keeping the code simple and standardized

**Comment by Toilal** [comment]
`Date.current()` could be added too.

**Pull request merged**
