### PR TITLE
fix: Date.name should be "Date"

### LINKED ISSUE #21: Breaks mongoose
I've been running into hard to track issues with mongoose dates being saved as `Object` of `{ _id: ObjectId(...) }` instead of actual dates.

I've since found this: https://github.com/alexandr2110pro/jest-date-mock-mongoose-friendly

Not sure why the author didn't make it a PR or if there are any downsides to his approach, but just wanted to let leave this here for whoever might run into the same issue.

### PR DESCRIPTION
**Pull request by andreialecu**
Fixes #21

### CODE REVIEW

**Comment by hustcc** [comment]
thanks.

**Comment by epegzz** [comment]
@hustcc which yesterday were you referring to exactly? 😆

**Comment by hustcc** [comment]
> @hustcc which yesterday were you referring to exactly? 😆

busy days, sorry for late, v1.0.8 released.

**Comment by epegzz** [comment]
Awesome @hustcc, thanks! 🎉

**Pull request merged**
